version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    env_file:
      - on peut spécifier ici le chemin du .env si le fichier n'est pas au même niveau
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup:/backup
      - ./script:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
